version: 2

project_name: moonshine

before:
  hooks:
    - go mod tidy

builds:
  - id: moonshine
    main: ./cmd/moonshine
    binary: moonshine
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: pyrorhythm
    name: moonshine
  draft: false
  prerelease: auto

homebrew_casks:
  - name: moonshine
    repository:
      owner: pyrorhythm
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://pyrorhythm.dev/moonshine
    description: moonshine -- missing declarative package manager aggregator for MacOS
    license: MIT
    url:
      verified: https://github.com/pyrorhythm/moonshine
    generate_completions_from_executable:
      args:
        - completion
      shell_parameter_format: arg
      shells:
        - bash
        - zsh
        - fish
        - pwsh
